package Tokeniser;

public enum TokenTypes 
{
    TTEOF, 
    TCD24, TCONS, TTYPD, TTDEF, TARRD, TMAIN, TBEGN, TTEND, TARAY, TTTOF, TFUNC, TVOID, 
	TCNST, TINTG, TFLOT, TBOOL, TTFOR, TREPT, TUNTL, TTTDO, TWHIL, TIFTH, TELSE, TELIF, 
	TSWTH, TCASE, TDFLT, TBREK, TINPT, TPRNT, TPRLN, TRETN, TNOTT, TTAND, TTTOR, TTXOR, 
	TTRUE, TFALS, TCOMA, TLBRK, TRBRK, TLPAR, TRPAR, TEQUL, TPLUS, TMINS, TSTAR, TDIVD,  
	TPERC, TCART, TLESS, TGRTR, TCOLN, TSEMI, TDOTT, TLEQL, TGEQL, TNEQL, TEQEQ, TPLEQ, 
	TMNEQ, TSTEQ, TDVEQ, TIDEN, TILIT, TFLIT, TSTRG, 
	TUNDF
}
